In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix as CM

from sklearn import svm

from sklearn import metrics

#آدرس خودتون رو بدید با همین فرمت
proteinuria = pd.read_excel('datat3.xlsx')

proteinuria.head()

,gender,age,SBP,BMI,etiology of CKD,Hb,Alb,Cr,eGFR,CKD_stage,...,eGFR(6M),eGFR(12M),eGFR(18M),eGFR(24M),eGFR(30M),eGFR(36M),eGFR(last visit),average_obs,obsevasion_ duration,fclass
0,2,74,120.0,23.137669,2,12.0,4.0,1.20,89.981926,3,...,26.454698,24.331582,24.682189,21.614854,20.420524,20.420524,18.495328,25.275139,37,0
1,1,57,139.0,28.515625,2,15.9,4.8,0.84,88.330020,2,...,78.287758,71.343858,72.845992,71.908942,71.562914,67.225032,67.225032,72.392152,37,0
2,1,32,154.0,24.582701,4,14.4,4.4,0.87,86.973875,2,...,75.027238,69.595257,68.856399,72.901926,69.749275,69.171408,69.171408,72.694258,36,0
3,1,60,144.0,30.737407,2,14.4,4.7,2.22,86.874201,4,...,26.885061,24.917353,28.581660,29.237135,25.556002,25.183703,25.183703,26.485251,35,0
4,1,49,135.0,NaN,2,17.0,4.1,1.39,86.782629,3,...,46.978867,45.829455,41.488436,41.801561,38.106104,NaN,38.106104,43.081581,30,0

In [5]:
#ستون هایی که ماهیت کتگوریکال چندگانه دارند تبدیل به ستون های باینری می شوند
proteinuria2 = pd.get_dummies(proteinuria, columns=['etiologyCKD','CKD_stage',
                                                    'CKDcategory',
                                                    'dipproteinuria',
                                                   'UPCRcategory'])
proteinuria2 = proteinuria.copy()

KeyError: "['etiologyCKD', 'dipproteinuria', 'CKDcategory', 'UPCRcategory'] not in index"

In [5]:
proteinuria2.describe()

,gender,age,SBP,BMI,etiology of CKD,Hb,Alb,Cr,eGFR,CKD_stage,...,eGFR(6M),eGFR(12M),eGFR(18M),eGFR(24M),eGFR(30M),eGFR(36M),eGFR(last visit),average_obs,obsevasion_ duration,fclass
count,922.000000,922.000000,906.000000,824.000000,922.000000,920.000000,913.000000,922.000000,922.000000,922.000000,...,922.000000,794.000000,704.000000,654.000000,584.000000,521.000000,922.000000,922.000000,922.000000,922.000000
mean,1.299349,67.198482,139.252759,23.758726,2.289588,12.151196,3.894414,2.044219,32.202784,3.529284,...,33.239529,33.059983,34.211131,32.862312,33.210103,33.761584,29.742976,32.010457,27.759219,0.864425
std,0.458222,13.599462,21.985860,3.901078,1.011165,2.201092,0.594604,1.355863,18.682809,0.833415,...,18.303286,17.852024,18.536361,17.879399,17.971859,18.028255,19.678544,17.862929,11.561597,1.696920
min,1.000000,21.000000,69.000000,14.239943,1.000000,5.900000,1.500000,0.510000,3.447745,2.000000,...,2.831911,3.355162,2.934258,2.375881,3.273473,3.501755,2.375881,3.615122,5.000000,0.000000
25%,1.000000,61.000000,125.000000,21.175685,2.000000,10.500000,3.600000,1.200000,17.331546,3.000000,...,18.548588,18.950807,19.600798,18.069915,18.699730,19.306187,12.105818,17.314529,18.000000,0.000000
50%,1.000000,70.000000,136.000000,23.437427,2.000000,12.200000,4.000000,1.650000,29.093413,3.000000,...,30.737273,31.127031,31.543293,30.733135,31.201121,32.100193,26.670484,29.049012,36.000000,0.000000
75%,2.000000,77.000000,151.000000,25.821342,3.000000,13.700000,4.300000,2.467500,44.696295,4.000000,...,45.680731,45.851072,46.530742,45.857386,45.517721,46.452680,44.497736,44.976682,37.000000,1.000000
max,2.000000,93.000000,234.000000,40.261002,4.000000,18.000000,5.200000,13.320000,89.981926,5.000000,...,111.613997,98.010699,98.246766,93.205513,95.465616,105.271375,111.613997,91.077377,39.000000,6.000000

In [10]:
proteinuria2.isna().sum()

gender                    0
age                       0
SBP                      16
BMI                      98
etiology of CKD           0
Hb                        2
Alb                       9
Cr                        0
eGFR                      0
CKD_stage                 0
CKD category             64
dip-stick proteinuria    10
proteinuria              10
urinary occult blood     10
UPCR                     64
UPCR category            64
hypertension              0
prevalence of CVD         0
diabetes                  0
use of RAASi              1
use of CCB                0
use of diuretics          0
eGFR(0M)                  0
eGFR(6M)                  0
eGFR(12M)                 0
eGFR(18M)                 0
eGFR(24M)                 0
eGFR(30M)                 0
eGFR(36M)                 0
eGFR(last visit)          0
average_obs               0
obsevasion_ duration      0
fclass                    0
dtype: int64

In [9]:
#Fill eGFR

ff = proteinuria2.columns.get_loc("eGFR(0M)")

ll = proteinuria2.columns.get_loc("eGFR(last visit)")
 
for i in range(len(proteinuria2)):
    xx = proteinuria2.iloc[i, ff:ll+1]
    if xx.isnull().any() == True:
        proteinuria2.iloc[i, ff:ll+1] = xx.interpolate(method ='linear', limit_direction ='backward')

In [11]:
#fill other columns with column average
proteinuria2 = proteinuria2.apply(lambda x: x.fillna(x.mean()),axis=0)

In [12]:
 proteinuria2.isna().sum()

gender                   0
age                      0
SBP                      0
BMI                      0
etiology of CKD          0
Hb                       0
Alb                      0
Cr                       0
eGFR                     0
CKD_stage                0
CKD category             0
dip-stick proteinuria    0
proteinuria              0
urinary occult blood     0
UPCR                     0
UPCR category            0
hypertension             0
prevalence of CVD        0
diabetes                 0
use of RAASi             0
use of CCB               0
use of diuretics         0
eGFR(0M)                 0
eGFR(6M)                 0
eGFR(12M)                0
eGFR(18M)                0
eGFR(24M)                0
eGFR(30M)                0
eGFR(36M)                0
eGFR(last visit)         0
average_obs              0
obsevasion_ duration     0
fclass                   0
dtype: int64

In [13]:
proteinuria2 = proteinuria2.apply(pd.to_numeric)

In [14]:
proteinuria2.to_csv('prepared Data.csv', index=False)